export type R2BucketRegion = 'apac' | 'eeur' | 'enam' | 'wnam' | 'weur';

export const preferredBuckets: { [key: string]: R2BucketRegion[] } = {
  AMS: ['weur', 'eeur'],
  ATL: ['enam'],
  BKK: ['apac'],
  BOM: ['apac'],
  BOS: ['enam'],
  BRU: ['eeur', 'weur'],
  BUF: ['enam'],
  CDG: ['eeur', 'weur'],
  CPH: ['eeur', 'weur'],
  DEN: ['enam', 'wnam'],
  DFW: ['enam', 'wnam'],
  DME: ['eeur', 'weur', 'apac'],
  DUB: ['eeur', 'weur'],
  DUS: ['eeur', 'weur'],
  EWR: ['enam'],
  EZE: ['enam', 'wnam'],
  FRA: ['eeur', 'weur'],
  GRU: ['enam'],
  HAM: ['apac', 'weur', 'eeur'],
  HKG: ['apac'],
  HYD: ['apac'],
  IAD: ['enam'],
  IST: ['eeur', 'weur'],
  KEF: ['eeur', 'weur'],
  KHH: ['apac'],
  KIX: ['apac'],
  LAS: ['enam', 'wnam'],
  LAX: ['wnam'],
  LHR: ['eeur', 'weur'],
  MAD: ['eeur', 'weur'],
  MAN: ['eeur', 'weur'],
  MBA: ['apac', 'weur', 'eeur'],
  MIA: ['enam'],
  MSP: ['enam', 'wnam'],
  MUC: ['eeur', 'weur'],
  MXP: ['eeur', 'weur'],
  NRT: ['apac'],
  ORD: ['enam', 'wnam'],
  OSL: ['weur', 'eeur'],
  OTP: ['eeur', 'apac'],
  PER: ['apac'],
  RIX: ['eeur', 'weur'],
  SEA: ['enam', 'wnam'],
  SIN: ['apac'],
  SJC: ['wnam'],
  SOF: ['eeur'],
  STR: ['eeur', 'weur'],
  SYD: ['apac', 'wnam'],
  VIE: ['eeur', 'weur'],
  WAW: ['eeur', 'weur'],
  YUL: ['enam'],
  YVR: ['wnam'],
  YYZ: ['enam'],
  ZRH: ['eeur', 'weur'],
};
