export type R2BucketRegion = 'apac' | 'eeur' | 'enam' | 'wnam' | 'weur' | 'oc';

export const preferredBuckets: { [key: string]: R2BucketRegion[] } = {
  ABQ: ['enam'],
  ADB: ['eeur'],
  AKL: ['wnam', 'oc'],
  ALA: ['eeur'],
  ALG: ['eeur'],
  AMM: ['eeur'],
  AMS: ['weur'],
  ANC: ['wnam'],
  ARN: ['eeur'],
  ATH: ['eeur'],
  ATL: ['enam'],
  AUS: ['wnam'],
  BKK: ['apac', 'oc'],
  BNU: ['weur'],
  BOD: ['eeur'],
  BOG: ['wnam'],
  BOM: ['apac', 'oc'],
  BOS: ['enam'],
  BRU: ['weur'],
  BSB: ['wnam'],
  BUF: ['enam'],
  BUD: ['eeur'],
  CBR: ['apac', 'oc'],
  CDG: ['weur'],
  CGK: ['apac', 'oc'],
  CLT: ['enam'],
  CMB: ['apac'],
  COK: ['apac'],
  CPH: ['weur'],
  DAC: ['apac'],
  DEN: ['wnam'],
  DFW: ['enam'],
  DME: ['weur'],
  DUB: ['weur'],
  DUS: ['weur'],
  EBB: ['weur'],
  EVN: ['eeur'],
  EWR: ['enam'],
  EZE: ['enam'],
  FRA: ['weur'],
  GIG: ['enam'],
  GRU: ['enam'],
  GVA: ['weur'],
  GYE: ['enam'],
  HAM: ['weur'],
  HFA: ['eeur'],
  HKG: ['apac', 'oc'],
  HYD: ['apac'],
  IAD: ['enam'],
  ICN: ['apac', 'oc'],
  IST: ['weur'],
  JAX: ['enam'],
  JNB: ['enam', 'eeur'],
  KBP: ['eeur'],
  KEF: ['weur'],
  KHH: ['apac'],
  KIX: ['apac'],
  KTM: ['apac'],
  KUL: ['apac', 'oc'],
  LAS: ['wnam'],
  LAX: ['wnam'],
  LCA: ['eeur'],
  LHR: ['weur'],
  LIS: ['weur'],
  LUX: ['weur'],
  LYS: ['weur'],
  MAA: ['apac'],
  MAD: ['weur'],
  MAN: ['weur'],
  MBA: ['weur'],
  MCI: ['enam'],
  MEL: ['wnam', 'oc'],
  MIA: ['enam'],
  MNL: ['apac', 'oc'],
  MRS: ['weur'],
  MSP: ['enam'],
  MUC: ['weur'],
  MXP: ['weur'],
  NOU: ['wnam', 'oc'],
  NRT: ['apac', 'oc'],
  OKC: ['wnam'],
  ORD: ['enam'],
  OSL: ['weur'],
  OTP: ['eeur'],
  PER: ['apac', 'oc'],
  PRG: ['weur'],
  PTY: ['enam'],
  RDU: ['enam'],
  RIC: ['enam'],
  RIX: ['eeur'],
  SCL: ['enam', 'weur'],
  SEA: ['wnam'],
  SIN: ['apac', 'oc'],
  SJC: ['wnam'],
  SMF: ['wnam'],
  SOF: ['eeur'],
  STL: ['enam'],
  STR: ['eeur'],
  SYD: ['wnam', 'oc'],
  TBS: ['eeur'],
  TGU: ['enam'],
  TLV: ['eeur'],
  TPE: ['apac', 'oc'],
  UDI: ['enam', 'weur'],
  UIO: ['enam', 'weur'],
  VIE: ['eeur'],
  VNO: ['eeur'],
  WAW: ['weur'],
  YHZ: ['enam'],
  YUL: ['enam'],
  YVR: ['wnam'],
  YYC: ['wnam'],
  YYZ: ['enam'],
  ZRH: ['weur'],
};
