interface WorkerEnv
  extends Omit<Env, 'ENVIRONMENT' | 'PMTILES_FILE_NAME' | 'PMTILES_FILE_HASH' | 'VMMETRICS_API_TOKEN'> {
  ENVIRONMENT: string;
  PMTILES_FILE_NAME: string;
  PMTILES_FILE_HASH: string;
  VMMETRICS_API_TOKEN: string;
}
