// Generated by Wrangler on Wed Aug 07 2024 15:42:16 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	PMTILES_FILE_NAME: "v1.pmtiles";
	PMTILES_FILE_HASH: "example-dev-hash";
	BUCKET: R2Bucket;
	CF_VERSION_METADATA: { id: string; tag: string };
}
