// Generated by Wrangler on Mon Aug 12 2024 22:15:36 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	PMTILES_FILE_NAME: "v1.pmtiles";
	PMTILES_FILE_HASH: "example-dev-hash";
	ENVIRONMENT: "development";
	BUCKET: R2Bucket;
	CF_VERSION_METADATA: { id: string; tag: string };
}
