// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	DEPLOYMENT_KEY: "20240812";
	ENVIRONMENT: "prod";
	BUCKET_WNAM: R2Bucket;
	BUCKET_ENAM: R2Bucket;
	BUCKET_WEUR: R2Bucket;
	BUCKET_EEUR: R2Bucket;
	BUCKET_APAC: R2Bucket;
	BUCKET_OC: R2Bucket;
	D1_WNAM: D1Database;
	D1_ENAM: D1Database;
	D1_WEUR: D1Database;
	D1_EEUR: D1Database;
	D1_APAC: D1Database;
	D1_OC: D1Database;
}
