{
 "title": "Tileserver Colos (Bucket Response Times)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "colo", "query": { "query": "label_values(colo)" } }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "colo" },
  { "type": "text", "gridPos": { "h": 8, "w": 1, "x": 0, "y": 1 }, "options": { "content": "# $colo" } },
  {
   "title": "Tile Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(tiles_get_tile_duration{colo=~\"$colo\"}[10m])",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.95, tiles_get_tile_duration{colo=~\"$colo\"}[10m])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.99, tiles_get_tile_duration{colo=~\"$colo\"}[10m])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.80, tiles_get_tile_duration{colo=~\"$colo\"}[10m])",
     "legendFormat": "p80"
    }
   ]
  },
  {
   "title": "Requests served by each regional bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$region/$total", "type": "math" }
   ]
  },
  {
   "title": "Requests served by each regional bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile(0.95, r2_storage_get_weur_duration{colo=\"$colo\"}[10m])",
     "legendFormat": "weur"
    },
    {
     "expr": "quantile(0.95, r2_storage_get_eeur_duration{colo=\"$colo\"}[10m])",
     "legendFormat": "eeur"
    },
    {
     "expr": "quantile(0.95, r2_storage_get_apac_duration{colo=\"$colo\"}[10m])",
     "legendFormat": "apac"
    },
    {
     "expr": "quantile(0.95, r2_storage_get_enam_duration{colo=\"$colo\"}[10m])",
     "legendFormat": "enam"
    },
    {
     "expr": "quantile(0.95, r2_storage_get_wnam_duration{colo=\"$colo\"}[10m])",
     "legendFormat": "wnam"
    },
    {
     "expr": "quantile(0.95, r2_storage_get_oc_duration{colo=\"$colo\"}[10m])",
     "legendFormat": "oc"
    }
   ]
  },
  {
   "title": "Requests served by each regional bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(r2_storage_get_weur_duration{colo=\"$colo\"}[24h])",
     "legendFormat": "weur"
    },
    {
     "expr": "avg(r2_storage_get_eeur_duration{colo=\"$colo\"}[24h])",
     "legendFormat": "eeur"
    },
    {
     "expr": "avg(r2_storage_get_apac_duration{colo=\"$colo\"}[24h])",
     "legendFormat": "apac"
    },
    {
     "expr": "avg(r2_storage_get_enam_duration{colo=\"$colo\"}[24h])",
     "legendFormat": "enam"
    },
    {
     "expr": "avg(r2_storage_get_wnam_duration{colo=\"$colo\"}[24h])",
     "legendFormat": "wnam"
    },
    {
     "expr": "avg(r2_storage_get_oc_duration{colo=\"$colo\"}[24h])",
     "legendFormat": "oc"
    }
   ]
  },
  {
   "title": "Requests per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time(tiles_handle_request_invocation{colo=\"$colo\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, tiles_handle_request_duration{colo=~\"$colo\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(tiles_handle_request_invocation{colo=~\"$colo\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}