{
 "title": "Tileserver",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(tiles_tile_request_errors[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Request Duration > 1.5s / Continent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(continent) (avg_over_time(tiles_tile_request_duration[$__interval])) > 1500",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Percentile Request Duration (5 min average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum by (vmrange) (histogram_over_time(tiles_handle_request_duration[1m])))",
     "legendFormat": "80th Percentile"
    },
    {
     "expr": "sum(sum_over_time(tiles_handle_request_duration[1m])) / sum(count_over_time(tiles_handle_request_duration[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (vmrange) (histogram_over_time(tiles_handle_request_duration[1m])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (vmrange) (histogram_over_time(tiles_handle_request_duration[1m])))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "RPS / Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(continent) (count_over_time(tiles_handle_request_invocation[1h])) / 1800",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(count_over_time(tiles_handle_request_invocation[1h])) / 1800",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Duration > 2s / Colo (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(colo) (tiles_tile_request_duration > 2100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "D1 p99 Duration / Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (vmrange,served_by_region) (histogram_over_time(d1_query_duration{database_key=\"\"}[1m])))",
     "legendFormat": "replica-{{served_by_region}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (vmrange,database_key) (histogram_over_time(d1_query_duration{database_key!=\"\"}[1m])))",
     "legendFormat": "geo-{{database_key}}"
    }
   ]
  },
  {
   "title": "%requests > x seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$1second/$total", "type": "math" },
    { "expression": "$2second/$total", "type": "math" },
    { "expression": "$500ms/$total", "type": "math" }
   ]
  },
  {
   "title": "Total Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "scalar(sum by() (count_over_time(tiles_handle_request_invocation[1h])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Request Duration / Zoom Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(tiles_tile_request_duration[1m])) by (z) / sum(count_over_time(tiles_tile_request_duration[1m])) by (z)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count / Zoom Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "(count by(z) (count_over_time(tiles_tile_request_invocation[1h])) or 0) + (count by(z) (count_over_time(tiles_cdn_hit_count{request_type=\"tile\"}[1h])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(count(count_over_time(tiles_style_request_invocation[1h])) or 0) + count(count_over_time(tiles_cdn_hit_count{request_type=\"style\"}[1h]))",
     "legendFormat": "Styles"
    },
    {
     "expr": "(sum(count_over_time(tiles_json_request_invocation[1h])) or 0) + sum(count_over_time(tiles_cdn_hit_count{request_type=\"json\"}[1h]))",
     "legendFormat": "Json"
    }
   ]
  },
  {
   "title": "Request Percentage / Zoom Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$z / $total",
     "reducer": "mean",
     "type": "math"
    }
   ]
  }
 ]
}