{
 "title": "Tileserver Colos",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "colo", "query": { "query": "label_values(colo)" } }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Percentage cached requests by z level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(z) (count_over_time(tiles_cdn_hit_count{request_type=\"tile\"}[1h])) / on(z) (sum by(z) (count_over_time(tiles_tile_request_invocation[1h])) + on(z) sum by(z) (count_over_time(tiles_cdn_hit_count{request_type=\"tile\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage cached requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(count_over_time(tiles_json_request_invocation[1h])) or 0",
     "legendFormat": "Json Uncached"
    },
    {
     "expr": "sum(count_over_time(tiles_style_request_invocation[1h])) or 0",
     "legendFormat": "Styles Uncached"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation[1h])) or 0",
     "legendFormat": "Tiles Uncached"
    },
    {
     "expr": "sum(count_over_time(tiles_handle_request_duration[1h])) or 0",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(count_over_time(tiles_cdn_hit_count{request_type=\"json\"}[1h])) or 0",
     "legendFormat": "Json Cached"
    },
    {
     "expr": "sum(count_over_time(tiles_cdn_hit_count{request_type=\"style\"}[1h])) or 0",
     "legendFormat": "Styles Cached"
    },
    {
     "expr": "sum(count_over_time(tiles_cdn_hit_count{request_type=\"tile\"}[1h])) or 0",
     "legendFormat": "Tiles Cached"
    }
   ]
  },
  {
   "title": "Uncached tile requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"0\"}[24h]))",
     "legendFormat": "tilez0"
    },
    {
     "expr": "sum(count_over_time(tiles_json_request_invocation[24h]))",
     "legendFormat": "json"
    },
    {
     "expr": "sum(count_over_time(tiles_style_request_invocation[24h]))",
     "legendFormat": "styles"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"1\"}[24h]))",
     "legendFormat": "tilez1"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"2\"}[24h]))",
     "legendFormat": "tilez2"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"3\"}[24h]))",
     "legendFormat": "tilesz3"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"4\"}[24h]))",
     "legendFormat": "tilesz4"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"5\"}[24h]))",
     "legendFormat": "tilesz5"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"6\"}[24h]))",
     "legendFormat": "tilesz6"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"7\"}[24h]))",
     "legendFormat": "tilesz7"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"8\"}[24h]))",
     "legendFormat": "tilesz8"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"9\"}[24h]))",
     "legendFormat": "tilesz9"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"10\"}[24h]))",
     "legendFormat": "tilesz10"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"11\"}[24h]))",
     "legendFormat": "tilesz11"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"12\"}[24h]))",
     "legendFormat": "tilesz12"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"13\"}[24h]))",
     "legendFormat": "tilesz13"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"14\"}[24h]))",
     "legendFormat": "tilesz14"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{z=\"15\"}[24h]))",
     "legendFormat": "tilesz15"
    },
    {
     "expr": "sum(count_over_time(tiles_handle_request_duration[24h]))",
     "legendFormat": "total"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "colo" },
  { "type": "text", "gridPos": { "h": 8, "w": 1, "x": 0, "y": 10 }, "options": { "content": "# $colo" } },
  {
   "title": "Average get tile duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, tiles_get_tile_duration{colo=~\"$colo\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tile Lookup Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(tiles_get_leaf_directory_duration{colo=\"$colo\"}[1m]))",
     "legendFormat": "kvget"
    },
    {
     "expr": "avg(avg_over_time(tiles_find_tile_leaf_directory_duration{colo=\"$colo\"}[1m]))",
     "legendFormat": "kvcompute"
    },
    {
     "expr": "max(max_over_time(tiles_d1_lookup_duration{colo=\"$colo\"}[1m]))",
     "legendFormat": "d1"
    }
   ]
  },
  {
   "title": "Requests served by each regional bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, r2_storage_get_weur_duration{colo=\"$colo\"}[10m]))",
     "legendFormat": "weur"
    },
    {
     "expr": "avg(quantile_over_time(0.95, r2_storage_get_eeur_duration{colo=\"$colo\"}[10m]))",
     "legendFormat": "eeur"
    },
    {
     "expr": "avg(quantile_over_time(0.95, r2_storage_get_apac_duration{colo=\"$colo\"}[10m]))",
     "legendFormat": "apac"
    },
    {
     "expr": "avg(quantile_over_time(0.95, r2_storage_get_enam_duration{colo=\"$colo\"}[10m]))",
     "legendFormat": "enam"
    },
    {
     "expr": "avg(quantile_over_time(0.95, r2_storage_get_wnam_duration{colo=\"$colo\"}[10m]))",
     "legendFormat": "wnam"
    },
    {
     "expr": "avg(quantile_over_time(0.95, r2_storage_get_oc_duration{colo=\"$colo\"}[10m]))",
     "legendFormat": "oc"
    }
   ]
  },
  {
   "title": "Percentage uncached requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(count_over_time(tiles_json_request_invocation{colo=\"$colo\"}[6h])) or 0",
     "legendFormat": "Json Uncached"
    },
    {
     "expr": "sum(count_over_time(tiles_style_request_invocation{colo=\"$colo\"}[6h])) or 0",
     "legendFormat": "Styles Uncached"
    },
    {
     "expr": "sum(count_over_time(tiles_tile_request_invocation{colo=\"$colo\"}[6h])) or 0",
     "legendFormat": "Tiles Uncached"
    },
    {
     "expr": "sum(count_over_time(tiles_cdn_hit_count{request_type=\"json\", colo=\"$colo\"}[6h])) or 0",
     "legendFormat": "Json Cached"
    },
    {
     "expr": "sum(count_over_time(tiles_cdn_hit_count{request_type=\"style\", colo=\"$colo\"}[6h])) or 0",
     "legendFormat": "Styles Cached"
    },
    {
     "expr": "sum(count_over_time(tiles_cdn_hit_count{request_type=\"tile\", colo=\"$colo\"}[6h])) or 0",
     "legendFormat": "Tiles Cached"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "sum(count_over_time(tiles_handle_request_duration{colo=~\"$colo\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(tiles_handle_request_duration{colo=~\"$colo\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(tiles_handle_request_duration{colo=~\"$colo\"}[30d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}